weights: weights\yolov5n.pt
cfg: ''
data: C:\Users\tlatonf\Desktop\obb0811\yolov5_obb\datasets\roboflow\data.yaml
hyp: data\hyps\obb\hyp.finetune_dota.yaml
epochs: 100
batch_size: 128
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: cpu
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp2
